language: ruby
cache: bundler
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.4"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.4"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.7"
notifications:
  email: false

